data_module:
  train_file: '/teamspace/studios/this_studio/datasets/uint16_optimized_balanced_train_data.h5'
  test_file: '/teamspace/studios/this_studio/dataset/test_data.h5'
  batch_size: 512
  dtype: !!python/name:numpy.uint16 ''
  num_workers: 2
  seed: 50
  split_ratio: 
    - 0.8
    - 0.2
model:
  input_channels: 6
  initial_channels: 32
  embedding_size: 128
  num_blocks: 4
  num_classes: 1
  dropout_rate: 0.5
loss_functions:
  center:
    params: 
      num_classes: 2
      feat_dim: 128
      lambda_c: 0.03
    weight: 1.0
  focal:
    params: 
      alpha: 0.25
      gamma: 2.0
    weight: 1.0
optimizer:
  type: 'AdamW'
  lr: 0.001
  weight_decay: 1.0e-5
scheduler:
  type: 'ReduceLROnPlateau'
  mode: 'max'
  factor: 0.1
  patience: 5
  verbose: True